# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/619/bin/cmake

# The command to remove a file.
RM = /snap/cmake/619/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/giulio/silkworm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/giulio/silkworm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/619/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/619/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/619/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/619/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/619/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/619/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/snap/cmake/619/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/snap/cmake/619/bin/cpack --config ./CPackSourceConfig.cmake /home/giulio/silkworm/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/619/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/619/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giulio/silkworm/CMakeFiles /home/giulio/silkworm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giulio/silkworm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/giulio/silkworm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/secp256k1.dir/build.make CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named evmone

# Build rule for target.
evmone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evmone
.PHONY : evmone

# fast build rule for target.
evmone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evmone.dir/build.make CMakeFiles/evmone.dir/build
.PHONY : evmone/fast

#=============================================================================
# Target rules for targets named ff

# Build rule for target.
ff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ff
.PHONY : ff

# fast build rule for target.
ff/fast:
	$(MAKE) $(MAKESILENT) -f libff/libff/CMakeFiles/ff.dir/build.make libff/libff/CMakeFiles/ff.dir/build
.PHONY : ff/fast

#=============================================================================
# Target rules for targets named cborcpp

# Build rule for target.
cborcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cborcpp
.PHONY : cborcpp

# fast build rule for target.
cborcpp/fast:
	$(MAKE) $(MAKESILENT) -f cbor-cpp/CMakeFiles/cborcpp.dir/build.make cbor-cpp/CMakeFiles/cborcpp.dir/build
.PHONY : cborcpp/fast

#=============================================================================
# Target rules for targets named instructions

# Build rule for target.
instructions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instructions
.PHONY : instructions

# fast build rule for target.
instructions/fast:
	$(MAKE) $(MAKESILENT) -f evmone/evmc/lib/instructions/CMakeFiles/instructions.dir/build.make evmone/evmc/lib/instructions/CMakeFiles/instructions.dir/build
.PHONY : instructions/fast

#=============================================================================
# Target rules for targets named loader

# Build rule for target.
loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loader
.PHONY : loader

# fast build rule for target.
loader/fast:
	$(MAKE) $(MAKESILENT) -f evmone/evmc/lib/loader/CMakeFiles/loader.dir/build.make evmone/evmc/lib/loader/CMakeFiles/loader.dir/build
.PHONY : loader/fast

#=============================================================================
# Target rules for targets named silkworm

# Build rule for target.
silkworm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm
.PHONY : silkworm

# fast build rule for target.
silkworm/fast:
	$(MAKE) $(MAKESILENT) -f silkworm/CMakeFiles/silkworm.dir/build.make silkworm/CMakeFiles/silkworm.dir/build
.PHONY : silkworm/fast

#=============================================================================
# Target rules for targets named silkworm_tg_api

# Build rule for target.
silkworm_tg_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm_tg_api
.PHONY : silkworm_tg_api

# fast build rule for target.
silkworm_tg_api/fast:
	$(MAKE) $(MAKESILENT) -f tg_api/CMakeFiles/silkworm_tg_api.dir/build.make tg_api/CMakeFiles/silkworm_tg_api.dir/build
.PHONY : silkworm_tg_api/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) $(MAKESILENT) -f cmd/CMakeFiles/unit_test.dir/build.make cmd/CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

evmone/lib/evmone/analysis.o: evmone/lib/evmone/analysis.cpp.o

.PHONY : evmone/lib/evmone/analysis.o

# target to build an object file
evmone/lib/evmone/analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evmone.dir/build.make CMakeFiles/evmone.dir/evmone/lib/evmone/analysis.cpp.o
.PHONY : evmone/lib/evmone/analysis.cpp.o

evmone/lib/evmone/analysis.i: evmone/lib/evmone/analysis.cpp.i

.PHONY : evmone/lib/evmone/analysis.i

# target to preprocess a source file
evmone/lib/evmone/analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evmone.dir/build.make CMakeFiles/evmone.dir/evmone/lib/evmone/analysis.cpp.i
.PHONY : evmone/lib/evmone/analysis.cpp.i

evmone/lib/evmone/analysis.s: evmone/lib/evmone/analysis.cpp.s

.PHONY : evmone/lib/evmone/analysis.s

# target to generate assembly for a file
evmone/lib/evmone/analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evmone.dir/build.make CMakeFiles/evmone.dir/evmone/lib/evmone/analysis.cpp.s
.PHONY : evmone/lib/evmone/analysis.cpp.s

evmone/lib/evmone/instructions.o: evmone/lib/evmone/instructions.cpp.o

.PHONY : evmone/lib/evmone/instructions.o

# target to build an object file
evmone/lib/evmone/instructions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evmone.dir/build.make CMakeFiles/evmone.dir/evmone/lib/evmone/instructions.cpp.o
.PHONY : evmone/lib/evmone/instructions.cpp.o

evmone/lib/evmone/instructions.i: evmone/lib/evmone/instructions.cpp.i

.PHONY : evmone/lib/evmone/instructions.i

# target to preprocess a source file
evmone/lib/evmone/instructions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evmone.dir/build.make CMakeFiles/evmone.dir/evmone/lib/evmone/instructions.cpp.i
.PHONY : evmone/lib/evmone/instructions.cpp.i

evmone/lib/evmone/instructions.s: evmone/lib/evmone/instructions.cpp.s

.PHONY : evmone/lib/evmone/instructions.s

# target to generate assembly for a file
evmone/lib/evmone/instructions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evmone.dir/build.make CMakeFiles/evmone.dir/evmone/lib/evmone/instructions.cpp.s
.PHONY : evmone/lib/evmone/instructions.cpp.s

secp256k1/src/secp256k1.o: secp256k1/src/secp256k1.c.o

.PHONY : secp256k1/src/secp256k1.o

# target to build an object file
secp256k1/src/secp256k1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/secp256k1.dir/build.make CMakeFiles/secp256k1.dir/secp256k1/src/secp256k1.c.o
.PHONY : secp256k1/src/secp256k1.c.o

secp256k1/src/secp256k1.i: secp256k1/src/secp256k1.c.i

.PHONY : secp256k1/src/secp256k1.i

# target to preprocess a source file
secp256k1/src/secp256k1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/secp256k1.dir/build.make CMakeFiles/secp256k1.dir/secp256k1/src/secp256k1.c.i
.PHONY : secp256k1/src/secp256k1.c.i

secp256k1/src/secp256k1.s: secp256k1/src/secp256k1.c.s

.PHONY : secp256k1/src/secp256k1.s

# target to generate assembly for a file
secp256k1/src/secp256k1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/secp256k1.dir/build.make CMakeFiles/secp256k1.dir/secp256k1/src/secp256k1.c.s
.PHONY : secp256k1/src/secp256k1.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... cborcpp"
	@echo "... evmone"
	@echo "... ff"
	@echo "... instructions"
	@echo "... loader"
	@echo "... secp256k1"
	@echo "... silkworm"
	@echo "... silkworm_tg_api"
	@echo "... unit_test"
	@echo "... evmone/lib/evmone/analysis.o"
	@echo "... evmone/lib/evmone/analysis.i"
	@echo "... evmone/lib/evmone/analysis.s"
	@echo "... evmone/lib/evmone/instructions.o"
	@echo "... evmone/lib/evmone/instructions.i"
	@echo "... evmone/lib/evmone/instructions.s"
	@echo "... secp256k1/src/secp256k1.o"
	@echo "... secp256k1/src/secp256k1.i"
	@echo "... secp256k1/src/secp256k1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/giulio/silkworm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

